# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RLMnemonicBackupDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

 pod 'SnapKit'
 pod 'SVProgressHUD'
  # Pods for RLMnemonicBackupDemo

  target 'RLMnemonicBackupDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RLMnemonicBackupDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
